apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: rolervengador/remigio1000
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: devops
spec:
  selector:
    app: devops
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
